/* Reto 60 Educación — prototipo 3° básico */
(function(){
 const subjects=[
  {id:'math3',icon:'🔢',name:'Matemática',desc:'Números, operaciones, multiplicación, división, problemas y geometría.',topics:['Multiplicación','División','Resolución de problemas','Geometría','Medición y patrones']},
  {id:'science3',icon:'🔬',name:'Ciencias Naturales',desc:'Seres vivos, cuerpo humano, plantas, materia, Tierra y ambiente.',topics:['Seres vivos','Cuerpo humano','Plantas','Materia y energía','Tierra y ambiente']},
  {id:'history3',icon:'🇨🇱',name:'Historia y Geografía',desc:'Chile, territorio, comunidad, pueblos y orientación espacial.',topics:['Chile y territorio','Geografía','Pueblos y culturas','Vida en comunidad','Historia']},
  {id:'language3',icon:'📖',name:'Lenguaje',desc:'Comprensión lectora, vocabulario, ortografía y comunicación.',topics:['Comprensión lectora','Vocabulario','Ortografía','Gramática','Comunicación']}
 ];
 function close(){document.getElementById('r60Education')?.remove()}
 function shell(body){close();const el=document.createElement('div');el.id='r60Education';el.style.cssText='position:fixed;inset:0;z-index:100050;background:linear-gradient(160deg,#071026,#101b42);overflow:auto;color:white;font-family:Arial;padding:20px';el.innerHTML=`<div style="max-width:520px;margin:auto"><button id="eduBack" style="width:auto;background:#202b55;color:white;padding:11px 15px">← VOLVER</button>${body}</div>`;document.body.appendChild(el);el.querySelector('#eduBack').onclick=close;return el}
 function home(){const cards=subjects.map(s=>`<button data-subject="${s.id}" style="text-align:left;background:#17234d;color:white;border:1px solid #33447d;padding:18px"><b style="font-size:20px">${s.icon} ${s.name}</b><span style="display:block;color:#aeb9d9;font-size:12px;margin-top:7px;line-height:1.4">${s.desc}</span></button>`).join('');const el=shell(`<div style="text-align:center;padding:18px 0"><div style="color:#67d9ff;font-weight:900">🎓 RETO 60 EDUCACIÓN</div><h1 style="margin:8px">3.º Básico</h1><p style="color:#aeb9d9">Aprende · Practica · Supera tu récord</p></div><div style="background:#111a39;border:1px solid #2d3c72;border-radius:20px;padding:16px;margin-bottom:14px"><b>⭐ Economía educativa</b><div style="font-size:12px;color:#aeb9d9;margin-top:6px">Sin publicidad ni dinero real. Los puntos obtenidos aprendiendo servirán para mascotas, accesorios y recompensas.</div></div><div style="display:grid;gap:10px">${cards}</div><button id="eduTeacher" style="margin-top:18px;background:#ffb800">👩‍🏫 VISTA PROFESOR · DEMO</button>`);el.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>subject(b.dataset.subject));el.querySelector('#eduTeacher').onclick=teacher}
 function subject(id){const s=subjects.find(x=>x.id===id);if(!s)return;const topics=s.topics.map((t,i)=>`<div style="padding:14px;background:#17234d;border-radius:14px;margin:8px 0"><b>${i+1}. ${t}</b><span style="display:block;font-size:11px;color:#9ca8cb;margin-top:4px">Banco curricular en construcción</span></div>`).join('');const el=shell(`<div style="text-align:center;padding:18px 0"><div style="font-size:44px">${s.icon}</div><h1>${s.name}</h1><div style="color:#67d9ff;font-weight:900">3.º BÁSICO</div></div>${topics}<div style="padding:14px;color:#9ca8cb;font-size:12px;line-height:1.5">La arquitectura queda preparada para asociar cada pregunta con curso, asignatura, tema, dificultad y Objetivo de Aprendizaje.</div><button id="eduHome" style="background:#252c58;color:white">VER OTRAS ASIGNATURAS</button>`);el.querySelector('#eduHome').onclick=home}
 function teacher(){shell(`<div style="text-align:center;padding:18px 0"><div style="color:#67d9ff;font-weight:900">👩‍🏫 PANEL DOCENTE · PROTOTIPO</div><h1>3.º Básico B</h1><p style="color:#aeb9d9">Ejemplo visual — aún no son datos reales.</p></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div style="background:#17234d;padding:16px;border-radius:16px"><b>28</b><div style="font-size:11px;color:#9ca8cb">ALUMNOS</div></div><div style="background:#17234d;padding:16px;border-radius:16px"><b>74%</b><div style="font-size:11px;color:#9ca8cb">DESEMPEÑO DEMO</div></div></div><div style="background:#111a39;border-radius:18px;padding:16px;margin-top:12px"><h3>📊 Próximamente</h3><p style="color:#aeb9d9;line-height:1.5">Resultados por alumno, asignatura y tema; progreso histórico; fortalezas; contenidos que requieren refuerzo; participación y rachas.</p></div><button id="eduHome" style="background:#ffb800">VOLVER A 3.º BÁSICO</button>`).querySelector('#eduHome').onclick=home}
 function install(){if(document.getElementById('r60EducationButton'))return;const homeEl=document.getElementById('home');if(!homeEl)return;const first=homeEl.querySelector('.panel');if(!first)return;const p=document.createElement('div');p.className='panel';p.style.cssText='border:1px solid #2d78a5;background:linear-gradient(145deg,#101d42,#102c49)';p.innerHTML='<div style="color:#67d9ff;font-weight:900">🎓 NUEVO · PROTOTIPO</div><h2>RETO 60 EDUCACIÓN</h2><p>Aprende jugando por curso y asignatura.</p><button id="r60EducationButton" class="share">🎓 ENTRAR · 3.º BÁSICO</button><div class="small">Sin publicidad · Sin compras con dinero real</div>';first.insertAdjacentElement('afterend',p);p.querySelector('#r60EducationButton').onclick=home}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();window.R60Education={open:home};
})();