/* Reto 60 Educación — prototipo 3° básico */
(function(){
 const subjects=[
  {id:'math3',icon:'🔢',name:'Matemática',desc:'Números, operaciones, multiplicación, división, problemas, geometría, medición y patrones.',topics:['Multiplicación','División','Resolución de problemas','Geometría','Medición y patrones']},
  {id:'science3',icon:'🔬',name:'Ciencias Naturales',desc:'Seres vivos, cuerpo humano, plantas, materia, Tierra y ambiente.',topics:['Seres vivos','Cuerpo humano','Plantas','Materia y energía','Tierra y ambiente']},
  {id:'history3',icon:'🇨🇱',name:'Historia y Geografía',desc:'Chile, territorio, comunidad, pueblos y orientación espacial.',topics:['Chile y territorio','Geografía','Pueblos y culturas','Vida en comunidad','Historia']},
  {id:'language3',icon:'📖',name:'Lenguaje',desc:'Comprensión lectora, vocabulario, ortografía y comunicación.',topics:['Comprensión lectora','Vocabulario','Ortografía','Gramática','Comunicación']}
 ];
 const mathQuestions=[
  {topic:'Multiplicación',q:'¿Cuánto es 4 × 6?',a:['20','24','28','18'],c:1},{topic:'Multiplicación',q:'¿Cuánto es 7 × 3?',a:['21','18','24','28'],c:0},{topic:'Multiplicación',q:'5 + 5 + 5 + 5 equivale a…',a:['5 × 3','4 × 5','5 × 5','4 × 4'],c:1},{topic:'Multiplicación',q:'¿Cuánto es 8 × 5?',a:['35','45','40','30'],c:2},{topic:'Multiplicación',q:'¿Cuánto es 9 × 4?',a:['32','36','40','45'],c:1},{topic:'Multiplicación',q:'Hay 6 bolsas con 3 manzanas cada una. ¿Cuántas manzanas hay?',a:['9','12','18','24'],c:2},
  {topic:'División',q:'¿Cuánto es 24 ÷ 6?',a:['3','4','5','6'],c:1},{topic:'División',q:'18 dulces se reparten entre 3 niños por igual. ¿Cuántos recibe cada uno?',a:['5','6','7','9'],c:1},{topic:'División',q:'¿Cuánto es 35 ÷ 5?',a:['5','6','7','8'],c:2},{topic:'División',q:'Si 4 × 7 = 28, entonces 28 ÷ 7 =…',a:['3','4','5','7'],c:1},{topic:'División',q:'20 lápices se guardan en 5 cajas iguales. ¿Cuántos van en cada caja?',a:['4','5','10','15'],c:0},
  {topic:'Resolución de problemas',q:'Ana tiene 12 stickers y recibe 8 más. ¿Cuántos tiene ahora?',a:['18','20','22','24'],c:1},{topic:'Resolución de problemas',q:'Había 30 globos y se reventaron 9. ¿Cuántos quedan?',a:['19','20','21','22'],c:2},{topic:'Resolución de problemas',q:'En 5 mesas hay 4 niños en cada una. ¿Cuántos niños hay?',a:['9','15','20','25'],c:2},{topic:'Resolución de problemas',q:'Una caja tiene 24 jugos. Se reparten en 6 grupos iguales. ¿Cuántos jugos recibe cada grupo?',a:['3','4','5','6'],c:1},{topic:'Resolución de problemas',q:'Pedro ahorró $300 y luego $250. ¿Cuánto ahorró en total?',a:['$450','$500','$550','$650'],c:2},
  {topic:'Geometría',q:'¿Cuántos lados tiene un triángulo?',a:['2','3','4','5'],c:1},{topic:'Geometría',q:'¿Cuántos lados tiene un cuadrado?',a:['3','4','5','6'],c:1},{topic:'Geometría',q:'¿Cuál figura tiene 4 lados iguales?',a:['Triángulo','Cuadrado','Círculo','Pentágono'],c:1},{topic:'Geometría',q:'Un cubo es una figura…',a:['De una dimensión','De dos dimensiones','De tres dimensiones','Sin dimensiones'],c:2},
  {topic:'Medición y patrones',q:'¿Cuántos minutos tiene una hora?',a:['30','45','60','100'],c:2},{topic:'Medición y patrones',q:'Son las 3:30. ¿Cómo se dice también?',a:['Tres en punto','Tres y cuarto','Tres y media','Cuatro menos cuarto'],c:2},{topic:'Medición y patrones',q:'Completa el patrón: 5, 10, 15, 20, …',a:['21','22','25','30'],c:2},{topic:'Medición y patrones',q:'Completa: 100, 200, 300, …',a:['350','400','500','600'],c:1},{topic:'Medición y patrones',q:'¿Qué unidad usarías para medir el largo de un lápiz?',a:['Litros','Centímetros','Kilogramos','Horas'],c:1}
 ];
 let eduGame=null;
 function close(){document.getElementById('r60Education')?.remove()}
 function shell(body){close();const el=document.createElement('div');el.id='r60Education';el.style.cssText='position:fixed;inset:0;z-index:100050;background:linear-gradient(160deg,#071026,#101b42);overflow:auto;color:white;font-family:Arial;padding:20px';el.innerHTML=`<div style="max-width:520px;margin:auto"><button id="eduBack" style="width:auto;background:#202b55;color:white;padding:11px 15px">← VOLVER</button>${body}</div>`;document.body.appendChild(el);el.querySelector('#eduBack').onclick=()=>eduGame?finishMath(true):close();return el}
 function home(){eduGame=null;const cards=subjects.map(s=>`<button data-subject="${s.id}" style="text-align:left;background:#17234d;color:white;border:1px solid #33447d;padding:18px"><b style="font-size:20px">${s.icon} ${s.name}</b><span style="display:block;color:#aeb9d9;font-size:12px;margin-top:7px;line-height:1.4">${s.desc}</span></button>`).join('');const el=shell(`<div style="text-align:center;padding:18px 0"><div style="color:#67d9ff;font-weight:900">🎓 RETO 60 EDUCACIÓN</div><h1 style="margin:8px">3.º Básico</h1><p style="color:#aeb9d9">Aprende · Practica · Supera tu récord</p></div><div style="background:#111a39;border:1px solid #2d3c72;border-radius:20px;padding:16px;margin-bottom:14px"><b>⭐ Economía educativa</b><div style="font-size:12px;color:#aeb9d9;margin-top:6px">Sin publicidad ni dinero real. Los puntos obtenidos aprendiendo servirán para mascotas, accesorios y recompensas.</div></div><div style="display:grid;gap:10px">${cards}</div><button id="eduTeacher" style="margin-top:18px;background:#ffb800">👩‍🏫 VISTA PROFESOR · DEMO</button>`);el.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>subject(b.dataset.subject));el.querySelector('#eduTeacher').onclick=teacher}
 function subject(id){const s=subjects.find(x=>x.id===id);if(!s)return;if(id==='math3')return mathMenu();const topics=s.topics.map((t,i)=>`<div style="padding:14px;background:#17234d;border-radius:14px;margin:8px 0"><b>${i+1}. ${t}</b><span style="display:block;font-size:11px;color:#9ca8cb;margin-top:4px">Banco curricular en construcción</span></div>`).join('');const el=shell(`<div style="text-align:center;padding:18px 0"><div style="font-size:44px">${s.icon}</div><h1>${s.name}</h1><div style="color:#67d9ff;font-weight:900">3.º BÁSICO</div></div>${topics}<button id="eduHome" style="background:#252c58;color:white">VER OTRAS ASIGNATURAS</button>`);el.querySelector('#eduHome').onclick=home}
 function mathMenu(){const counts={};mathQuestions.forEach(q=>counts[q.topic]=(counts[q.topic]||0)+1);const topics=subjects[0].topics.map(t=>`<button data-topic="${t}" style="text-align:left;background:#17234d;color:white;border:1px solid #33447d;padding:15px;margin:6px 0"><b>🎯 ${t}</b><span style="display:block;font-size:11px;color:#9ca8cb;margin-top:4px">${counts[t]||0} preguntas · práctica de 60 segundos</span></button>`).join('');const el=shell(`<div style="text-align:center;padding:15px 0"><div style="font-size:46px">🔢</div><h1 style="margin:6px">Matemática</h1><div style="color:#67d9ff;font-weight:900">3.º BÁSICO</div><p style="color:#aeb9d9">Elige un tema o juega todo mezclado.</p></div><button id="mathAll" style="background:#ffb800;color:#111">⚡ RETO MATEMÁTICO · TODO MEZCLADO</button>${topics}<button id="eduHome" style="background:#252c58;color:white">← OTRAS ASIGNATURAS</button>`);el.querySelector('#mathAll').onclick=()=>startMath('Todo mezclado');el.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>startMath(b.dataset.topic));el.querySelector('#eduHome').onclick=home}
 function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
 function startMath(topic){let pool=topic==='Todo mezclado'?mathQuestions:mathQuestions.filter(q=>q.topic===topic);eduGame={topic,deck:shuffled(pool),score:0,correct:0,wrong:0,answered:0,seconds:60,timer:null,current:null};renderMathGame();nextMath();eduGame.timer=setInterval(()=>{if(!eduGame)return;eduGame.seconds--;const t=document.getElementById('eduTime');if(t)t.textContent=eduGame.seconds;if(eduGame.seconds<=0)finishMath(false)},1000)}
 function renderMathGame(){const el=shell(`<div style="text-align:center"><div style="color:#67d9ff;font-weight:900">🎓 3.º BÁSICO · MATEMÁTICA</div><div style="font-size:13px;color:#aeb9d9;margin-top:5px">${eduGame.topic}</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0"><div style="background:#17234d;border-radius:16px;padding:12px"><b style="font-size:28px;color:#ffb800"><span id="eduTime">60</span>s</b><div style="font-size:10px;color:#9ca8cb">TIEMPO</div></div><div style="background:#17234d;border-radius:16px;padding:12px"><b style="font-size:28px">⭐ <span id="eduScore">0</span></b><div style="font-size:10px;color:#9ca8cb">PUNTOS</div></div></div><div id="eduTopic" style="font-size:11px;color:#67d9ff;font-weight:900"></div><h2 id="eduQuestion" style="min-height:58px"></h2><div id="eduAnswers"></div><div style="font-size:11px;color:#9ca8cb;margin-top:15px">Correctas: <span id="eduCorrect">0</span> · Respondidas: <span id="eduAnswered">0</span></div></div>`);el.querySelector('#eduBack').textContent='← SALIR DE LA PARTIDA'}
 function nextMath(){if(!eduGame)return;if(!eduGame.deck.length)eduGame.deck=shuffled(eduGame.topic==='Todo mezclado'?mathQuestions:mathQuestions.filter(q=>q.topic===eduGame.topic));const q=eduGame.deck.pop();eduGame.current=q;document.getElementById('eduTopic').textContent='📘 '+q.topic;document.getElementById('eduQuestion').textContent=q.q;const a=document.getElementById('eduAnswers');a.innerHTML='';q.a.forEach((txt,i)=>{const b=document.createElement('button');b.textContent=txt;b.style.cssText='background:#252c58;color:white;margin:6px 0';b.onclick=()=>answerMath(i,b);a.appendChild(b)})}
 function answerMath(i,b){if(!eduGame)return;const ok=i===eduGame.current.c;eduGame.answered++;if(ok){eduGame.correct++;eduGame.score+=10;b.style.background='#21633d'}else{eduGame.wrong++;b.style.background='#74333b'}document.getElementById('eduScore').textContent=eduGame.score;document.getElementById('eduCorrect').textContent=eduGame.correct;document.getElementById('eduAnswered').textContent=eduGame.answered;setTimeout(nextMath,180)}
 function finishMath(cancel){if(!eduGame)return home();clearInterval(eduGame.timer);const g=eduGame;eduGame=null;if(cancel)return mathMenu();const pct=g.answered?Math.round(g.correct/g.answered*100):0;const old=Number(localStorage.getItem('r60edu_points')||0),earned=g.score;localStorage.setItem('r60edu_points',String(old+earned));localStorage.setItem('r60edu_math3_last',JSON.stringify({topic:g.topic,correct:g.correct,answered:g.answered,pct,score:g.score,date:new Date().toISOString()}));const el=shell(`<div style="text-align:center;padding:20px 0"><div style="font-size:55px">🏆</div><div style="color:#67d9ff;font-weight:900">3.º BÁSICO · MATEMÁTICA</div><h1>¡Reto completado!</h1><div style="font-size:52px;font-weight:900;color:#ffb800">${g.score}</div><div>puntos ganados</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:18px 0"><div style="background:#17234d;padding:15px;border-radius:15px"><b>${g.correct}/${g.answered}</b><div style="font-size:11px;color:#9ca8cb">CORRECTAS</div></div><div style="background:#17234d;padding:15px;border-radius:15px"><b>${pct}%</b><div style="font-size:11px;color:#9ca8cb">PRECISIÓN</div></div></div><div style="color:#aeb9d9;font-size:12px">⭐ Saldo educativo: ${old+earned} puntos</div><button id="eduAgain" style="background:#ffb800">🔁 JUGAR DE NUEVO</button><button id="eduMathMenu" style="background:#252c58;color:white">VER TEMAS DE MATEMÁTICA</button></div>`);el.querySelector('#eduAgain').onclick=()=>startMath(g.topic);el.querySelector('#eduMathMenu').onclick=mathMenu}
 function teacher(){shell(`<div style="text-align:center;padding:18px 0"><div style="color:#67d9ff;font-weight:900">👩‍🏫 PANEL DOCENTE · PROTOTIPO</div><h1>3.º Básico B</h1><p style="color:#aeb9d9">Ejemplo visual — aún no son datos reales.</p></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div style="background:#17234d;padding:16px;border-radius:16px"><b>28</b><div style="font-size:11px;color:#9ca8cb">ALUMNOS</div></div><div style="background:#17234d;padding:16px;border-radius:16px"><b>74%</b><div style="font-size:11px;color:#9ca8cb">DESEMPEÑO DEMO</div></div></div><div style="background:#111a39;border-radius:18px;padding:16px;margin-top:12px"><h3>📊 Próximamente</h3><p style="color:#aeb9d9;line-height:1.5">Resultados por alumno, asignatura y tema; progreso histórico; fortalezas; contenidos que requieren refuerzo; participación y rachas.</p></div><button id="eduHome" style="background:#ffb800">VOLVER A 3.º BÁSICO</button>`).querySelector('#eduHome').onclick=home}
 function install(){if(document.getElementById('r60EducationButton'))return;const homeEl=document.getElementById('home');if(!homeEl)return;const first=homeEl.querySelector('.panel');if(!first)return;const p=document.createElement('div');p.className='panel';p.style.cssText='border:1px solid #2d78a5;background:linear-gradient(145deg,#101d42,#102c49)';p.innerHTML='<div style="color:#67d9ff;font-weight:900">🎓 NUEVO · PROTOTIPO</div><h2>RETO 60 EDUCACIÓN</h2><p>Aprende jugando por curso y asignatura.</p><button id="r60EducationButton" class="share">🎓 ENTRAR · 3.º BÁSICO</button><div class="small">Sin publicidad · Sin compras con dinero real</div>';first.insertAdjacentElement('afterend',p);p.querySelector('#r60EducationButton').onclick=home}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();window.R60Education={open:home};
})();