/* Reto 60 player profile + achievements + level titles */
function reto60TitleForLevel(level){const titles=[{level:20,icon:'⚡',name:'Leyenda'},{level:10,icon:'🏆',name:'Maestro'},{level:5,icon:'🎓',name:'Experto'},{level:3,icon:'⚔️',name:'Competidor'},{level:2,icon:'🧠',name:'Curioso'},{level:1,icon:'🌱',name:'Novato'}];return titles.find(t=>level>=t.level)||titles[titles.length-1];}
function reto60NextTitle(level){return [{level:2,icon:'🧠',name:'Curioso'},{level:3,icon:'⚔️',name:'Competidor'},{level:5,icon:'🎓',name:'Experto'},{level:10,icon:'🏆',name:'Maestro'},{level:20,icon:'⚡',name:'Leyenda'}].find(t=>t.level>level)||null;}
function reto60ProfileStats(){const p=typeof reto60Progress==='function'?reto60Progress():{xp:0,best:0,level:1,base:0,next:100,pct:0};const points=Number(localStorage.getItem('reto60points')||0),streak=Number(localStorage.getItem('reto60streak')||0);const cloudMatches=Number(window.cloudPlayer?.matches_played||window.cloudPlayer?.matches||0),localMatches=Number(localStorage.getItem('reto60_local_matches')||0);const matches=Math.max(cloudMatches,localMatches,p.xp>0?1:0),name=(typeof playerShareName==='function'?playerShareName():localStorage.getItem('reto60_display_name'))||'Jugador';return {...p,points,streak,matches,name,title:reto60TitleForLevel(p.level)};}
function reto60Achievements(s){return [{id:'first_match',icon:'🎮',name:'Primera partida',desc:'Completa tu primera partida',ok:s.matches>=1},{id:'thousand_points',icon:'⭐',name:'Mil puntos',desc:'Alcanza 1.000 puntos acumulados',ok:s.points>=1000},{id:'centurion',icon:'🏆',name:'Centurión',desc:'Consigue un récord de 100 puntos',ok:s.best>=100},{id:'fire_week',icon:'🔥',name:'Semana de fuego',desc:'Mantén una racha de 7 días',ok:s.streak>=7},{id:'level_5',icon:'⚡',name:'Nivel 5',desc:'Alcanza el nivel 5',ok:s.level>=5}];}
function reto60CloseProfile(){document.getElementById('reto60ProfileOverlay')?.remove();}
function reto60OpenProfile(){reto60CloseProfile();const s=reto60ProfileStats(),ach=reto60Achievements(s),unlocked=ach.filter(a=>a.ok).length,nextTitle=reto60NextTitle(s.level);const overlay=document.createElement('div');overlay.id='reto60ProfileOverlay';overlay.style.cssText='position:fixed;inset:0;z-index:100002;background:rgba(4,7,18,.97);overflow:auto;padding:22px;font-family:Arial,sans-serif;color:white';overlay.innerHTML=`<div style="max-width:500px;margin:0 auto"><button id="reto60ProfileCloseTop" style="width:auto;padding:10px 14px;margin:0 0 14px;background:#252c58;color:white">← VOLVER</button><div style="text-align:center"><div style="font-size:15px;color:#aaa">👤 PERFIL DEL JUGADOR</div><h1>${s.name}</h1><div style="color:#ffb800;font-size:24px;font-weight:900">⚡ NIVEL ${s.level}</div><div>${s.title.icon} ${s.title.name}</div>${nextTitle?`<div style="font-size:12px;color:#aaa">Próximo título: ${nextTitle.icon} ${nextTitle.name} · Nivel ${nextTitle.level}</div>`:''}</div><div class="panel"><div>⭐ ${s.points} puntos · 🏆 ${s.best} récord · 🔥 ${s.streak} racha · 🎮 ${s.matches} partidas</div></div><div class="panel"><h2>🏅 Logros</h2><div>${unlocked} de ${ach.length} desbloqueados</div>${ach.map(a=>`<div style="padding:10px;margin-top:8px;background:#1d2347;border-radius:12px;opacity:${a.ok?1:.5}">${a.ok?a.icon:'🔒'} <b>${a.name}</b> · ${a.desc}</div>`).join('')}</div><button id="reto60ProfileClose" style="background:#252c58;color:white">CERRAR PERFIL</button></div>`;document.body.appendChild(overlay);overlay.querySelector('#reto60ProfileClose').onclick=reto60CloseProfile;overlay.querySelector('#reto60ProfileCloseTop').onclick=reto60CloseProfile;}
function reto60CheckAchievements(){return reto60Achievements(reto60ProfileStats())}
function reto60InstallProfile(){const home=document.getElementById('home');if(!home||document.getElementById('reto60ProfileButton'))return;const progress=document.getElementById('reto60ProgressBox'),b=document.createElement('button');b.id='reto60ProfileButton';b.className='restart';b.textContent='👤 VER MI PERFIL Y LOGROS';b.onclick=reto60OpenProfile;if(progress)progress.insertAdjacentElement('afterend',b);else home.querySelector('.stats')?.insertAdjacentElement('afterend',b);}
(function(){const boot=()=>reto60InstallProfile();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,50));else setTimeout(boot,50);})();
(function loadR60Rewards(){if(window.R60Rewards||document.querySelector('script[data-r60-rewards]'))return;const s=document.createElement('script');s.src=new URL('rewards.js',document.baseURI).href;s.dataset.r60Rewards='1';s.async=false;s.onload=()=>{window.R60Rewards?.install?.();window.R60Rewards?.render?.();};document.body.appendChild(s);})();
(function loadR60Store(){if(window.R60Store||document.querySelector('script[data-r60-store]'))return;const s=document.createElement('script');s.src=new URL('store.js?v=2',document.baseURI).href;s.dataset.r60Store='1';s.async=false;s.onload=()=>{window.R60Store?.install?.();loadR60GameBoosters();loadR60StoreEnhancements();};document.body.appendChild(s);})();
function loadR60GameBoosters(){if(window.R60GameBoosters||document.querySelector('script[data-r60-game-boosters]')){window.R60GameBoosters?.install?.();return;}const s=document.createElement('script');s.src=new URL('game-boosters.js',document.baseURI).href;s.dataset.r60GameBoosters='1';s.async=false;s.onload=()=>window.R60GameBoosters?.install?.();document.body.appendChild(s);}
function loadR60StoreEnhancements(){if(window.R60Pets||document.querySelector('script[data-r60-store-enhancements]'))return;const s=document.createElement('script');s.src=new URL('store-enhancements.js?v=1',document.baseURI).href;s.dataset.r60StoreEnhancements='1';s.async=false;document.body.appendChild(s);}
(function loadR60FriendChallengeUI(){if(window.R60FriendChallengeUI||document.querySelector('script[data-r60-friend-ui]'))return;const s=document.createElement('script');s.src=new URL('friend-challenge-ui.js',document.baseURI).href;s.dataset.r60FriendUi='1';s.async=false;s.onload=()=>window.R60FriendChallengeUI?.install?.();document.body.appendChild(s);})();
