const knowledgeQuestionPack = [
// GEOGRAFÍA
{q:"¿Cuál es la capital de Perú?",a:["Lima","Cusco","Arequipa","Trujillo"],c:0,category:"geography"},
{q:"¿Cuál es la capital de Colombia?",a:["Medellín","Cali","Bogotá","Cartagena"],c:2,category:"geography"},
{q:"¿Cuál es la capital de Uruguay?",a:["Salto","Montevideo","Punta del Este","Colonia"],c:1,category:"geography"},
{q:"¿Cuál es la capital de Ecuador?",a:["Guayaquil","Cuenca","Quito","Loja"],c:2,category:"geography"},
{q:"¿Cuál es la capital de México?",a:["Monterrey","Guadalajara","Ciudad de México","Puebla"],c:2,category:"geography"},
{q:"¿Cuál es la capital de Canadá?",a:["Toronto","Vancouver","Montreal","Ottawa"],c:3,category:"geography"},
{q:"¿Cuál es la capital de Australia?",a:["Sídney","Melbourne","Canberra","Perth"],c:2,category:"geography"},
{q:"¿Cuál es la capital de Portugal?",a:["Oporto","Lisboa","Braga","Coímbra"],c:1,category:"geography"},
{q:"¿Cuál es la capital de Alemania?",a:["Múnich","Hamburgo","Berlín","Fráncfort"],c:2,category:"geography"},
{q:"¿Cuál es la capital de Grecia?",a:["Atenas","Esparta","Patras","Salónica"],c:0,category:"geography"},
{q:"¿En qué continente está Brasil?",a:["África","América del Sur","Asia","Europa"],c:1,category:"geography"},
{q:"¿En qué continente está India?",a:["Asia","África","Europa","Oceanía"],c:0,category:"geography"},
{q:"¿En qué continente está Noruega?",a:["Asia","Europa","América","Oceanía"],c:1,category:"geography"},
{q:"¿Qué océano separa principalmente América de Europa y África?",a:["Pacífico","Índico","Atlántico","Ártico"],c:2,category:"geography"},
{q:"¿Qué cordillera recorre gran parte del oeste de Sudamérica?",a:["Alpes","Andes","Himalaya","Pirineos"],c:1,category:"geography"},
{q:"¿Qué río atraviesa Egipto?",a:["Amazonas","Danubio","Nilo","Misisipi"],c:2,category:"geography"},
{q:"¿En qué país se encuentra Machu Picchu?",a:["Bolivia","Perú","Ecuador","Chile"],c:1,category:"geography"},
{q:"¿En qué país se encuentra la ciudad de Barcelona?",a:["Portugal","España","Italia","Francia"],c:1,category:"geography"},
{q:"¿Qué país tiene forma de bota en los mapas de Europa?",a:["Grecia","Italia","Croacia","España"],c:1,category:"geography"},
{q:"¿Cuál es el desierto cálido más grande del mundo?",a:["Atacama","Gobi","Sahara","Kalahari"],c:2,category:"geography"},
// CIENCIA
{q:"¿Qué planeta está más cerca del Sol?",a:["Venus","Mercurio","Marte","Tierra"],c:1,category:"science"},
{q:"¿Qué planeta es famoso por sus anillos visibles?",a:["Marte","Saturno","Venus","Mercurio"],c:1,category:"science"},
{q:"¿Cuál es la estrella del sistema solar?",a:["Sirio","Polaris","Sol","Luna"],c:2,category:"science"},
{q:"¿Qué fuerza nos mantiene sobre la superficie terrestre?",a:["Magnetismo","Gravedad","Fricción","Electricidad"],c:1,category:"science"},
{q:"¿Qué gas absorben principalmente las plantas durante la fotosíntesis?",a:["Oxígeno","Helio","Dióxido de carbono","Hidrógeno"],c:2,category:"science"},
{q:"¿Qué gas liberan las plantas durante la fotosíntesis?",a:["Oxígeno","Nitrógeno","Metano","Helio"],c:0,category:"science"},
{q:"¿Cuál es el órgano más grande del cuerpo humano?",a:["Hígado","Pulmón","Piel","Corazón"],c:2,category:"science"},
{q:"¿Cuántos huesos tiene normalmente un adulto?",a:["106","206","306","406"],c:1,category:"science"},
{q:"¿Qué células de la sangre transportan principalmente oxígeno?",a:["Glóbulos rojos","Plaquetas","Neuronas","Glóbulos blancos"],c:0,category:"science"},
{q:"¿Qué órgano usamos principalmente para respirar?",a:["Riñones","Pulmones","Estómago","Páncreas"],c:1,category:"science"},
{q:"¿A qué temperatura se congela el agua pura a presión normal?",a:["0 °C","10 °C","32 °C","100 °C"],c:0,category:"science"},
{q:"¿A qué temperatura hierve el agua a nivel del mar?",a:["50 °C","75 °C","90 °C","100 °C"],c:3,category:"science"},
{q:"¿Cuál es el símbolo químico del oxígeno?",a:["Ox","O","Og","O2H"],c:1,category:"science"},
{q:"¿Cuál es el símbolo químico del hierro?",a:["Ir","Hi","Fe","He"],c:2,category:"science"},
{q:"¿Qué partícula tiene carga eléctrica negativa?",a:["Protón","Neutrón","Electrón","Fotón"],c:2,category:"science"},
{q:"¿Cómo se llama el cambio de líquido a gas?",a:["Condensación","Evaporación","Fusión","Solidificación"],c:1,category:"science"},
{q:"¿Cómo se llama el cambio de sólido a líquido?",a:["Fusión","Sublimación","Condensación","Evaporación"],c:0,category:"science"},
{q:"¿Qué instrumento permite observar estrellas y planetas lejanos?",a:["Microscopio","Telescopio","Estetoscopio","Termómetro"],c:1,category:"science"},
{q:"¿Qué ciencia estudia los seres vivos?",a:["Geología","Biología","Astronomía","Meteorología"],c:1,category:"science"},
{q:"¿Qué ciencia estudia los astros y el universo?",a:["Botánica","Astronomía","Zoología","Anatomía"],c:1,category:"science"},
// HISTORIA
{q:"¿Qué civilización construyó Machu Picchu?",a:["Maya","Azteca","Inca","Romana"],c:2,category:"history"},
{q:"¿Qué civilización construyó las pirámides de Guiza?",a:["Egipcia","Romana","Inca","Vikinga"],c:0,category:"history"},
{q:"¿En qué año llegó Cristóbal Colón a América?",a:["1392","1492","1592","1692"],c:1,category:"history"},
{q:"¿Qué imperio tuvo a Roma como centro?",a:["Imperio romano","Imperio inca","Imperio azteca","Imperio mongol"],c:0,category:"history"},
{q:"¿Quién fue el primer emperador romano?",a:["Nerón","Augusto","Julio César","Trajano"],c:1,category:"history"},
{q:"¿Qué ciudad antigua quedó sepultada por la erupción del Vesubio en el año 79?",a:["Pompeya","Atenas","Esparta","Cartago"],c:0,category:"history"},
{q:"¿En qué país comenzó la Revolución Industrial?",a:["Francia","Alemania","Gran Bretaña","España"],c:2,category:"history"},
{q:"¿En qué año comenzó la Primera Guerra Mundial?",a:["1905","1914","1918","1939"],c:1,category:"history"},
{q:"¿En qué año terminó la Primera Guerra Mundial?",a:["1914","1916","1918","1920"],c:2,category:"history"},
{q:"¿En qué año comenzó la Segunda Guerra Mundial en Europa?",a:["1918","1929","1939","1945"],c:2,category:"history"},
{q:"¿En qué año terminó la Segunda Guerra Mundial?",a:["1942","1943","1945","1948"],c:2,category:"history"},
{q:"¿Qué muro cayó en 1989 y simbolizó el fin de una era en Europa?",a:["Muro de Adriano","Muro de Berlín","Gran Muralla","Muro de las Lamentaciones"],c:1,category:"history"},
{q:"¿Quién lideró la independencia de varios territorios del norte de Sudamérica?",a:["Simón Bolívar","Napoleón Bonaparte","Abraham Lincoln","Winston Churchill"],c:0,category:"history"},
{q:"¿En qué país nació Simón Bolívar?",a:["Colombia","Venezuela","Perú","Ecuador"],c:1,category:"history"},
{q:"¿Qué antigua civilización desarrolló la democracia en Atenas?",a:["Griega","Egipcia","Fenicia","Persa"],c:0,category:"history"},
{q:"¿Quién fue conocido como el Libertador de Argentina, Chile y Perú?",a:["José de San Martín","Miguel Hidalgo","Benito Juárez","Francisco de Miranda"],c:0,category:"history"},
{q:"¿Qué cultura precolombina tuvo Tenochtitlán como capital?",a:["Inca","Maya","Azteca","Olmeca"],c:2,category:"history"},
{q:"¿Qué invento de Gutenberg revolucionó la difusión de libros en Europa?",a:["Telégrafo","Imprenta de tipos móviles","Radio","Máquina de vapor"],c:1,category:"history"},
{q:"¿Qué navegante completó la expedición que realizó la primera vuelta al mundo?",a:["Juan Sebastián Elcano","Marco Polo","James Cook","Américo Vespucio"],c:0,category:"history"},
{q:"¿Qué acontecimiento francés comenzó en 1789?",a:["Revolución Francesa","Revolución Industrial","Guerra de Crimea","Restauración Meiji"],c:0,category:"history"},
// TECNOLOGÍA
{q:"¿Qué significan las siglas CPU en informática?",a:["Unidad Central de Procesamiento","Control Personal Universal","Programa Central de Usuario","Unidad de Copia Principal"],c:0,category:"technology"},
{q:"¿Qué dispositivo se usa normalmente para mover el puntero de una computadora?",a:["Router","Ratón","Impresora","Altavoz"],c:1,category:"technology"},
{q:"¿Qué dispositivo muestra visualmente la información de una computadora?",a:["Monitor","Micrófono","Teclado","Router"],c:0,category:"technology"},
{q:"¿Qué componente almacena datos de forma temporal mientras se ejecutan programas?",a:["RAM","Monitor","Ratón","Ventilador"],c:0,category:"technology"},
{q:"¿Qué tecnología inalámbrica se usa habitualmente para conectar dispositivos a una red local?",a:["HDMI","Wi‑Fi","USB","VGA"],c:1,category:"technology"},
{q:"¿Qué tecnología inalámbrica de corto alcance conecta auriculares y teléfonos?",a:["Bluetooth","Ethernet","HDMI","SATA"],c:0,category:"technology"},
{q:"¿Qué significa URL en el contexto de la web?",a:["Localizador Uniforme de Recursos","Unidad Remota Local","Registro Universal de Línea","Red Unificada Lógica"],c:0,category:"technology"},
{q:"¿Qué protocolo aparece normalmente al inicio de una dirección web segura?",a:["FTP","HTTPX","HTTPS","SMTP"],c:2,category:"technology"},
{q:"¿Cuál de estos es un navegador web?",a:["Chrome","Excel","Photoshop","Bluetooth"],c:0,category:"technology"},
{q:"¿Cuál de estos es un sistema operativo?",a:["Windows","Wi‑Fi","HTML","USB"],c:0,category:"technology"},
{q:"¿Qué lenguaje estructura el contenido básico de una página web?",a:["HTML","SQL","PNG","MP3"],c:0,category:"technology"},
{q:"¿Qué lenguaje se usa principalmente para dar estilo visual a páginas web?",a:["CSS","PDF","CSV","DNS"],c:0,category:"technology"},
{q:"¿Qué lenguaje permite añadir comportamiento interactivo en muchas páginas web?",a:["JPEG","JavaScript","HTTP","ZIP"],c:1,category:"technology"},
{q:"¿Qué dispositivo dirige tráfico entre redes?",a:["Router","Monitor","Teclado","Escáner"],c:0,category:"technology"},
{q:"¿Qué unidad equivale a 8 bits?",a:["Byte","Kilómetro","Píxel","Hercio"],c:0,category:"technology"},
{q:"¿Cuál de estos formatos se usa comúnmente para imágenes?",a:["JPEG","MP3","TXT","WAV"],c:0,category:"technology"},
{q:"¿Cuál de estos formatos se usa comúnmente para audio?",a:["PNG","MP3","HTML","CSS"],c:1,category:"technology"},
{q:"¿Qué periférico se usa principalmente para introducir texto?",a:["Teclado","Monitor","Proyector","Altavoz"],c:0,category:"technology"},
{q:"¿Qué servicio traduce nombres de dominio a direcciones IP?",a:["DNS","USB","GPU","PDF"],c:0,category:"technology"},
{q:"¿Qué componente está especializado en procesar gráficos?",a:["GPU","SSD","RAM","NIC"],c:0,category:"technology"},
// ENTRETENIMIENTO
{q:"¿Cómo se llama el ogro verde protagonista de una famosa saga animada?",a:["Shrek","Simba","Woody","Nemo"],c:0,category:"entertainment"},
{q:"¿Qué personaje de Disney pierde un zapato de cristal?",a:["Ariel","Cenicienta","Mulán","Elsa"],c:1,category:"entertainment"},
{q:"¿Cómo se llama el vaquero de Toy Story?",a:["Buzz","Woody","Rex","Andy"],c:1,category:"entertainment"},
{q:"¿Cómo se llama el compañero espacial de Woody en Toy Story?",a:["Buzz Lightyear","Mike Wazowski","Shrek","Olaf"],c:0,category:"entertainment"},
{q:"¿Qué película animada tiene a Simba como protagonista?",a:["Aladdín","El Rey León","Bambi","Tarzán"],c:1,category:"entertainment"},
{q:"¿Cómo se llama la escuela de magia de Harry Potter?",a:["Narnia","Hogwarts","Camelot","Nevermore"],c:1,category:"entertainment"},
{q:"¿Qué superhéroe es conocido como el Hombre Murciélago?",a:["Superman","Batman","Flash","Thor"],c:1,category:"entertainment"},
{q:"¿Qué superhéroe utiliza un escudo con una estrella?",a:["Iron Man","Hulk","Capitán América","Aquaman"],c:2,category:"entertainment"},
{q:"¿Cómo se llama el muñeco de nieve de Frozen?",a:["Olaf","Sven","Kristoff","Hans"],c:0,category:"entertainment"},
{q:"¿Qué película presenta un parque con dinosaurios clonados?",a:["Jurassic Park","Avatar","Titanic","Gladiator"],c:0,category:"entertainment"},
{q:"¿Qué saga cinematográfica incluye a Darth Vader?",a:["Star Wars","Rocky","Matrix","Indiana Jones"],c:0,category:"entertainment"},
{q:"¿Qué personaje vive en una piña debajo del mar?",a:["Bob Esponja","Garfield","Snoopy","Pikachu"],c:0,category:"entertainment"},
{q:"¿Cómo se llama el pez protagonista de Buscando a Nemo?",a:["Dory","Nemo","Marlin","Bruce"],c:1,category:"entertainment"},
{q:"¿Qué instrumento tiene normalmente seis cuerdas?",a:["Guitarra","Flauta","Trompeta","Batería"],c:0,category:"entertainment"},
{q:"¿Qué familia de instrumentos incluye el violín?",a:["Cuerda","Percusión","Viento metal","Teclado"],c:0,category:"entertainment"},
{q:"¿Cómo se llama el premio de cine entregado por la Academia de Hollywood?",a:["Oscar","Grammy","Emmy","Tony"],c:0,category:"entertainment"},
{q:"¿Qué premio está especialmente asociado con la industria musical estadounidense?",a:["Grammy","Oscar","Pulitzer","Nobel"],c:0,category:"entertainment"},
{q:"¿Qué personaje de videojuegos es un fontanero con gorra roja?",a:["Sonic","Mario","Link","Kirby"],c:1,category:"entertainment"},
{q:"¿Qué personaje de videojuegos es un erizo azul?",a:["Sonic","Mario","Pac-Man","Donkey Kong"],c:0,category:"entertainment"},
{q:"¿Qué criatura amarilla es una de las mascotas más famosas de Pokémon?",a:["Pikachu","Charmander","Squirtle","Meowth"],c:0,category:"entertainment"}
];