const questions = [
  {q:"¿Cuál es el planeta más grande del sistema solar?",a:["Marte","Júpiter","Saturno","Venus"],c:1},
  {q:"¿Cuánto es 12 × 8?",a:["86","96","106","88"],c:1},
  {q:"¿Cuál es la capital de Argentina?",a:["Córdoba","Buenos Aires","Mendoza","Rosario"],c:1},
  {q:"¿Cuál es la capital de Chile?",a:["Valparaíso","Santiago","Concepción","Antofagasta"],c:1},
  {q:"¿Cuál es la capital de Venezuela?",a:["Maracaibo","Valencia","Caracas","Barquisimeto"],c:2},
  {q:"¿Cuántos continentes se suelen reconocer?",a:["5","6","7","8"],c:2},
  {q:"¿Qué océano es el más grande?",a:["Atlántico","Índico","Pacífico","Ártico"],c:2},
  {q:"¿Cuánto es 15 + 27?",a:["40","42","44","46"],c:1},
  {q:"¿Cuánto es 9 × 7?",a:["56","63","72","69"],c:1},
  {q:"¿Cuánto es 100 ÷ 4?",a:["20","25","30","40"],c:1},
  {q:"¿Qué animal es conocido como el rey de la selva?",a:["Tigre","León","Jaguar","Elefante"],c:1},
  {q:"¿Cuál es el satélite natural de la Tierra?",a:["Marte","Sol","Luna","Venus"],c:2},
  {q:"¿Qué gas necesitamos principalmente para respirar?",a:["Oxígeno","Helio","Hidrógeno","Neón"],c:0},
  {q:"¿Cuántos lados tiene un hexágono?",a:["5","6","7","8"],c:1},
  {q:"¿Cuál es el resultado de 11²?",a:["111","121","131","101"],c:1},
  {q:"¿Qué instrumento mide la temperatura?",a:["Barómetro","Termómetro","Cronómetro","Altímetro"],c:1},
  {q:"¿En qué continente está Egipto?",a:["Asia","Europa","África","Oceanía"],c:2},
  {q:"¿Cuál es la capital de Francia?",a:["Roma","Madrid","París","Lyon"],c:2},
  {q:"¿Cuál es la capital de Japón?",a:["Kioto","Tokio","Osaka","Nagoya"],c:1},
  {q:"¿Cuántos minutos tiene una hora?",a:["50","60","70","100"],c:1},
  {q:"¿Qué color resulta de mezclar azul y amarillo?",a:["Verde","Naranja","Morado","Rojo"],c:0},
  {q:"¿Cuál es el metal cuyo símbolo químico es Au?",a:["Plata","Oro","Cobre","Aluminio"],c:1},
  {q:"¿Cuál es el símbolo químico del agua?",a:["CO2","O2","H2O","NaCl"],c:2},
  {q:"¿Cuántos días tiene una semana?",a:["5","6","7","8"],c:2},
  {q:"¿Cuál es el número primo más pequeño?",a:["0","1","2","3"],c:2},
  {q:"¿Qué planeta es conocido como el planeta rojo?",a:["Mercurio","Marte","Júpiter","Neptuno"],c:1},
  {q:"¿Cuánto es 144 ÷ 12?",a:["10","11","12","14"],c:2},
  {q:"¿Cuál es la capital de Italia?",a:["Milán","Roma","Venecia","Nápoles"],c:1},
  {q:"¿Cuántas horas tiene un día?",a:["12","18","24","36"],c:2},
  {q:"¿Qué órgano bombea la sangre por el cuerpo?",a:["Pulmón","Cerebro","Corazón","Hígado"],c:2},
  {q:"¿Cuál es la capital de España?",a:["Barcelona","Madrid","Sevilla","Valencia"],c:1},
  {q:"¿Cuál es la capital de Portugal?",a:["Oporto","Lisboa","Braga","Coímbra"],c:1},
  {q:"¿Cuál es la capital de Colombia?",a:["Medellín","Cali","Bogotá","Cartagena"],c:2},
  {q:"¿Cuál es la capital de Perú?",a:["Cusco","Lima","Arequipa","Trujillo"],c:1},
  {q:"¿Cuál es la capital de Brasil?",a:["Río de Janeiro","São Paulo","Brasilia","Salvador"],c:2},
  {q:"¿Cuál es la capital de México?",a:["Monterrey","Ciudad de México","Guadalajara","Puebla"],c:1},
  {q:"¿Cuál es la capital de Canadá?",a:["Toronto","Vancouver","Ottawa","Montreal"],c:2},
  {q:"¿Cuál es la capital de Australia?",a:["Sídney","Melbourne","Canberra","Perth"],c:2},
  {q:"¿Cuál es la capital de Alemania?",a:["Múnich","Berlín","Hamburgo","Fráncfort"],c:1},
  {q:"¿Cuál es la capital del Reino Unido?",a:["Manchester","Londres","Liverpool","Edimburgo"],c:1},
  {q:"¿Cuál es la capital de Grecia?",a:["Atenas","Esparta","Salónica","Patras"],c:0},
  {q:"¿Cuál es la capital de Egipto?",a:["Alejandría","El Cairo","Luxor","Guiza"],c:1},
  {q:"¿Cuál es la capital de China?",a:["Shanghái","Pekín","Cantón","Shenzhen"],c:1},
  {q:"¿Cuál es la capital de Corea del Sur?",a:["Busan","Seúl","Incheon","Daegu"],c:1},
  {q:"¿Cuál es la capital de Uruguay?",a:["Punta del Este","Montevideo","Salto","Colonia"],c:1},
  {q:"¿Cuál es la capital de Paraguay?",a:["Asunción","Encarnación","Luque","San Lorenzo"],c:0},
  {q:"¿Cuál es la capital de Ecuador?",a:["Guayaquil","Quito","Cuenca","Loja"],c:1},
  {q:"¿Cuál es la capital constitucional de Bolivia?",a:["La Paz","Sucre","Santa Cruz","Cochabamba"],c:1},
  {q:"¿Qué planeta está más cerca del Sol?",a:["Venus","Mercurio","Marte","Tierra"],c:1},
  {q:"¿Qué planeta tiene anillos muy visibles?",a:["Marte","Saturno","Venus","Mercurio"],c:1},
  {q:"¿Cuántos planetas tiene el sistema solar?",a:["7","8","9","10"],c:1},
  {q:"¿Cuál es la estrella del sistema solar?",a:["Sirio","Polaris","El Sol","Betelgeuse"],c:2},
  {q:"¿Qué fuerza nos mantiene sobre la superficie terrestre?",a:["Magnetismo","Gravedad","Fricción","Electricidad"],c:1},
  {q:"¿Qué órgano usamos principalmente para respirar?",a:["Riñones","Pulmones","Estómago","Páncreas"],c:1},
  {q:"¿Qué órgano controla gran parte de las funciones del cuerpo?",a:["Cerebro","Hígado","Corazón","Bazo"],c:0},
  {q:"¿Cuántos huesos tiene normalmente un adulto?",a:["186","206","226","246"],c:1},
  {q:"¿Qué vitamina produce la piel con ayuda de la luz solar?",a:["Vitamina A","Vitamina C","Vitamina D","Vitamina K"],c:2},
  {q:"¿Qué gas absorben las plantas para la fotosíntesis?",a:["Oxígeno","Dióxido de carbono","Helio","Nitrógeno"],c:1},
  {q:"¿Qué parte de la planta absorbe agua del suelo?",a:["Flor","Raíz","Fruto","Hoja"],c:1},
  {q:"¿Cuál es el animal terrestre más grande?",a:["Jirafa","Elefante africano","Rinoceronte","Hipopótamo"],c:1},
  {q:"¿Cuál es el mamífero más grande del mundo?",a:["Elefante","Ballena azul","Orca","Tiburón ballena"],c:1},
  {q:"¿Qué animal es un mamífero?",a:["Delfín","Tiburón","Pulpo","Trucha"],c:0},
  {q:"¿Qué animal cambia de oruga a adulto mediante metamorfosis?",a:["Mariposa","Araña","Lagarto","Ratón"],c:0},
  {q:"¿Cuántas patas tiene una araña?",a:["6","8","10","12"],c:1},
  {q:"¿Cuántos lados tiene un triángulo?",a:["3","4","5","6"],c:0},
  {q:"¿Cuántos lados tiene un pentágono?",a:["4","5","6","7"],c:1},
  {q:"¿Cuántos grados tiene un ángulo recto?",a:["45","60","90","180"],c:2},
  {q:"¿Cuánto vale una docena?",a:["10","12","20","24"],c:1},
  {q:"¿Cuántos centímetros hay en un metro?",a:["10","100","1000","10000"],c:1},
  {q:"¿Cuántos metros hay en un kilómetro?",a:["100","500","1000","10000"],c:2},
  {q:"¿Cuántos segundos tiene un minuto?",a:["30","60","90","100"],c:1},
  {q:"¿Cuántos meses tiene un año?",a:["10","11","12","13"],c:2},
  {q:"¿Qué mes tiene menos días en un año común?",a:["Enero","Febrero","Abril","Junio"],c:1},
  {q:"¿Qué instrumento se usa para observar objetos muy pequeños?",a:["Telescopio","Microscopio","Periscopio","Sextante"],c:1},
  {q:"¿Qué instrumento se usa para observar astros lejanos?",a:["Microscopio","Telescopio","Termómetro","Brújula"],c:1},
  {q:"¿Qué instrumento indica el norte magnético?",a:["Brújula","Regla","Balanza","Cronómetro"],c:0},
  {q:"¿Qué mide un barómetro?",a:["Temperatura","Presión atmosférica","Velocidad","Distancia"],c:1},
  {q:"¿Cuál es el símbolo químico del oxígeno?",a:["O","Ox","O2H","Og"],c:0},
  {q:"¿Cuál es el símbolo químico del hierro?",a:["Ir","Fe","Hi","F"],c:1},
  {q:"¿Cuál es el símbolo químico de la plata?",a:["Ag","Pt","Au","Pl"],c:0},
  {q:"¿Qué elemento tiene el símbolo Na?",a:["Nitrógeno","Sodio","Neón","Níquel"],c:1},
  {q:"¿Qué elemento tiene el símbolo C?",a:["Calcio","Carbono","Cobre","Cloro"],c:1},
  {q:"¿A qué temperatura se congela el agua pura a nivel del mar?",a:["0 °C","10 °C","32 °C","100 °C"],c:0},
  {q:"¿A qué temperatura hierve el agua aproximadamente a nivel del mar?",a:["50 °C","80 °C","100 °C","120 °C"],c:2},
  {q:"¿Cuál es el océano entre América y Europa?",a:["Pacífico","Atlántico","Índico","Ártico"],c:1},
  {q:"¿Cuál es el continente más grande por superficie?",a:["África","Asia","Europa","Oceanía"],c:1},
  {q:"¿En qué continente está Brasil?",a:["América del Sur","África","Europa","Asia"],c:0},
  {q:"¿En qué continente está España?",a:["Asia","Europa","África","Oceanía"],c:1},
  {q:"¿En qué continente está Japón?",a:["Europa","Asia","África","América"],c:1},
  {q:"¿Qué cordillera recorre gran parte del oeste de Sudamérica?",a:["Alpes","Andes","Himalaya","Pirineos"],c:1},
  {q:"¿Cuál es la montaña más alta sobre el nivel del mar?",a:["K2","Everest","Aconcagua","Kilimanjaro"],c:1},
  {q:"¿Cuál es el idioma oficial mayoritario de Brasil?",a:["Español","Portugués","Francés","Italiano"],c:1},
  {q:"¿Quién escribió Don Quijote de la Mancha?",a:["Miguel de Cervantes","Pablo Neruda","Jorge Luis Borges","Gabriel García Márquez"],c:0},
  {q:"¿Quién escribió Cien años de soledad?",a:["Mario Vargas Llosa","Gabriel García Márquez","Julio Cortázar","Isabel Allende"],c:1},
  {q:"¿Quién pintó la Mona Lisa?",a:["Miguel Ángel","Leonardo da Vinci","Picasso","Van Gogh"],c:1},
  {q:"¿Quién pintó La noche estrellada?",a:["Van Gogh","Dalí","Monet","Goya"],c:0},
  {q:"¿Qué instrumento musical tiene teclas blancas y negras?",a:["Violín","Piano","Flauta","Trompeta"],c:1},
  {q:"¿Cuántas cuerdas tiene normalmente una guitarra clásica?",a:["4","5","6","8"],c:2},
  {q:"¿Qué deporte se juega con una raqueta y una pelota amarilla?",a:["Tenis","Béisbol","Golf","Rugby"],c:0},
  {q:"¿Cuántos jugadores por equipo hay en cancha al inicio de un partido de fútbol?",a:["9","10","11","12"],c:2},
  {q:"¿En qué deporte se utiliza una canasta y un balón?",a:["Baloncesto","Tenis","Béisbol","Hockey"],c:0},
  {q:"¿Cuántos aros tiene el símbolo olímpico?",a:["4","5","6","7"],c:1},
  {q:"¿Qué pieza de ajedrez se mueve en forma de L?",a:["Alfil","Caballo","Torre","Reina"],c:1},
  {q:"¿Qué pieza de ajedrez debe protegerse para evitar el jaque mate?",a:["Reina","Rey","Torre","Caballo"],c:1},
  {q:"¿Qué color se obtiene al mezclar rojo y azul?",a:["Verde","Morado","Naranja","Amarillo"],c:1},
  {q:"¿Qué dispositivo se usa para escribir texto en una computadora?",a:["Monitor","Teclado","Altavoz","Router"],c:1},
  {q:"¿Qué significa CPU en informática?",a:["Unidad Central de Procesamiento","Control Principal Universal","Código Personal Único","Unidad de Programa Central"],c:0},
  {q:"¿Qué red global conecta millones de dispositivos?",a:["Bluetooth","Internet","GPS","NFC"],c:1},
  {q:"¿Qué formato se usa comúnmente para páginas web?",a:["HTML","MP3","JPEG","ZIP"],c:0},
  {q:"¿Qué lenguaje se usa comúnmente para dar estilo a páginas web?",a:["CSS","SQL","PDF","CSV"],c:0},
  {q:"¿Qué lenguaje se ejecuta comúnmente en navegadores para añadir interactividad?",a:["JavaScript","Excel","Photoshop","HTTP"],c:0}
];

// Banco matemático reconstruido de forma determinista para evitar alternativas duplicadas.
for(let x=11;x<=40;x++){const y=((x*7)%29)+3;const r=x+y;questions.push({q:`¿Cuánto es ${x} + ${y}?`,a:[String(r-2),String(r+10),String(r),String(r+2)],c:2});}
for(let x=25;x<=54;x++){const y=((x-25)*3)%18+5;const r=x-y;questions.push({q:`¿Cuánto es ${x} − ${y}?`,a:[String(r-1),String(r),String(r+1),String(r+5)],c:1});}
for(let x=3;x<=12;x++){for(let y=3;y<=12;y++){const r=x*y;const opts=[r-x,r,r+y,r+10];const uniq=[];for(const n of opts){let v=n;while(uniq.includes(v))v++;uniq.push(v);}questions.push({q:`¿Cuánto es ${x} × ${y}?`,a:uniq.map(String),c:1});}}
for(let d=2;d<=3;d++){for(let r=3;r<=12;r++){questions.push({q:`¿Cuánto es ${d*r} ÷ ${d}?`,a:[String(r-1),String(r),String(r+1),String(r+2)],c:1});}}
