/* Reto 60 rewards: R60 Coins + daily missions + daily chest + wallet (virtual, non-cash) */
(function(){
 const K={coins:'reto60_r60_coins',earned:'reto60_r60_lifetime_earned',day:'reto60_rewards_day',games:'reto60_daily_games',best:'reto60_daily_best',cats:'reto60_daily_categories',chest:'reto60_daily_chest',bonus:'reto60_daily_bonus',tx:'reto60_r60_transactions'};
 const today=()=>new Date().toISOString().slice(0,10),num=k=>Number(localStorage.getItem(k)||0),set=(k,v)=>localStorage.setItem(k,String(v));
 function reset(){if(localStorage.getItem(K.day)===today())return;localStorage.setItem(K.day,today());set(K.games,0);set(K.best,0);localStorage.setItem(K.cats,'[]');localStorage.removeItem(K.chest);localStorage.removeItem(K.bonus);}
 function coins(){return num(K.coins)}
 function lifetime(){if(localStorage.getItem(K.earned)===null)set(K.earned,coins());return num(K.earned)}
 function transactions(){try{return JSON.parse(localStorage.getItem(K.tx)||'[]')}catch(e){return[]}}
 function recordTx(amount,label){const list=transactions();list.unshift({amount:Number(amount)||0,label:label||'Recompensa R60',at:new Date().toISOString()});localStorage.setItem(K.tx,JSON.stringify(list.slice(0,50)));}
 function add(n,label){n=Number(n)||0;set(K.coins,coins()+n);if(n>0)set(K.earned,lifetime()+n);recordTx(n,label);render();return coins();}
 function missions(){reset();const games=num(K.games),best=num(K.best),cats=JSON.parse(localStorage.getItem(K.cats)||'[]');return [{id:'play3',icon:'🎮',name:'Juega 3 partidas',now:Math.min(games,3),goal:3,reward:8,ok:games>=3},{id:'score60',icon:'🏆',name:'Consigue 60 puntos',now:Math.min(best,60),goal:60,reward:6,ok:best>=60},{id:'categories2',icon:'🎯',name:'Juega 2 categorías',now:Math.min(cats.length,2),goal:2,reward:6,ok:cats.length>=2}];}
 function claimed(){return JSON.parse(localStorage.getItem('reto60_claimed_'+today())||'[]')} function claim(id){const m=missions().find(x=>x.id===id),c=claimed();if(!m?.ok||c.includes(id))return;c.push(id);localStorage.setItem('reto60_claimed_'+today(),JSON.stringify(c));add(m.reward,'Misión: '+m.name);toast(`🪙 +${m.reward} R60`,`Misión completada: ${m.name}`);render();}
 function chest(){reset();if(num(K.games)<1){toast('🔒 Cofre bloqueado','Completa tu primera partida del día.');return}if(localStorage.getItem(K.chest)){toast('🎁 Cofre abierto','Vuelve mañana para conseguir otro.');return}const rewards=[5,6,7,8,10,12],r=rewards[Math.floor(Math.random()*rewards.length)];localStorage.setItem(K.chest,String(r));add(r,'Cofre diario');toast(`🎁 ¡+${r} R60!`,'Premio del cofre diario');render();}
 function toast(title,text){document.getElementById('r60RewardToast')?.remove();const o=document.createElement('div');o.id='r60RewardToast';o.style.cssText='position:fixed;inset:0;z-index:100020;background:rgba(4,7,18,.92);display:flex;align-items:center;justify-content:center;padding:22px;color:white;font-family:Arial';o.innerHTML=`<div style="max-width:390px;width:100%;text-align:center;background:#151a35;border:2px solid #ffb800;border-radius:25px;padding:28px"><div style="font-size:31px;font-weight:900;color:#ffb800">${title}</div><p style="color:#bbb">${text}</p><button id="r60ToastClose" style="background:#ffb800;color:#111">CONTINUAR</button></div>`;document.body.appendChild(o);o.querySelector('#r60ToastClose').onclick=()=>o.remove();}
 function wallet(){document.getElementById('r60Wallet')?.remove();const tx=transactions(),o=document.createElement('div');o.id='r60Wallet';o.style.cssText='position:fixed;inset:0;z-index:100015;background:linear-gradient(160deg,#080b18,#151a38);overflow:auto;color:white;font-family:Arial;padding:22px';o.innerHTML=`<div style="max-width:500px;margin:auto"><button id="r60WalletClose" style="width:auto;background:#252c58;color:white;padding:12px 18px">← VOLVER</button><div style="text-align:center;margin:20px 0"><div style="font-size:18px;color:#aaa">🪙 MI BILLETERA</div><div style="font-size:48px;font-weight:900;color:#ffb800;margin-top:8px">${coins()} R60</div><div class="small">Saldo disponible</div></div><div class="panel" style="text-align:left"><h2>⚡ Cómo conseguir R60</h2><p>🎁 Abre el cofre diario después de jugar.</p><p>🎯 Completa las misiones de cada día.</p><p>🔥 Regresa diariamente para nuevas oportunidades.</p></div><div class="panel" style="text-align:left"><h2>📜 Movimientos</h2>${tx.length?tx.map(t=>`<div style="display:flex;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid #292f5c"><div><b>${t.label}</b></div><b>${t.amount>=0?'+':''}${t.amount} R60</b></div>`).join(''):'<p class="small">Tus próximas recompensas aparecerán aquí.</p>'}</div></div>`;document.body.appendChild(o);o.querySelector('#r60WalletClose').onclick=()=>o.remove();}
 function render(){reset();const box=document.getElementById('r60Rewards');if(!box)return;const c=claimed(),ms=missions();box.innerHTML=`<button id="r60WalletOpen" style="margin:0;padding:0;background:transparent;color:white;text-align:inherit"><div style="display:flex;justify-content:space-between;align-items:center"><div><b>🪙 R60 COINS</b><div class="small">Toca para abrir tu billetera</div></div><div style="font-size:25px;font-weight:900;color:#ffb800">${coins()}</div></div></button><button id="r60Chest" class="play">${localStorage.getItem(K.chest)?'🎁 COFRE DE HOY ABIERTO':num(K.games)>=1?'🎁 ABRIR COFRE DIARIO':'🔒 COFRE · JUEGA 1 PARTIDA'}</button><h3>🎯 Misiones de hoy</h3>${ms.map(m=>`<div style="background:#1d2347;border-radius:14px;padding:12px;margin-top:8px;text-align:left"><b>${m.icon} ${m.name}</b> · ${m.now}/${m.goal}${m.ok&&!c.includes(m.id)?`<button class="mini r60Claim" data-id="${m.id}">RECLAMAR +${m.reward} R60</button>`:''}</div>`).join('')}`;box.querySelector('#r60WalletOpen').onclick=wallet;box.querySelector('#r60Chest').onclick=chest;box.querySelectorAll('.r60Claim').forEach(b=>b.onclick=()=>claim(b.dataset.id));}
 function install(){const home=document.getElementById('home');if(!home||document.getElementById('r60Rewards'))return false;const box=document.createElement('div');box.id='r60Rewards';box.className='panel';home.querySelector('.stats')?.insertAdjacentElement('afterend',box);lifetime();render();return true;}
 window.R60Rewards={coins,lifetime,add,missions,render,install,wallet,transactions};
})();