/* Reto 60 Store — professional Preview UI + inventory */
(function(){
 const INV_KEY='reto60_inventory_v1',ACTIVE_TIME_KEY='reto60_time10_active',FOX_EQUIPPED_KEY='reto60_fox_equipped';
 const PRODUCTS=[{id:'time10',icon:'⏳',name:'+10 SEGUNDOS',kind:'POTENCIADOR',price:'USD 0.90',desc:'Obtén 10 segundos extra en tu próxima partida.',cls:'boost'},{id:'fox',icon:'🦊',name:'ZORRO R60',kind:'MASCOTA',price:'USD 2.99',desc:'Multiplica tus puntos x2 durante 10 segundos, una vez por partida.',cls:'fox'}];
 const R60_PRODUCTS=[{id:'special',icon:'🎟️',name:'Entrada especial',price:50,desc:'Acceso a retos y eventos especiales de Reto 60.'},{id:'streak',icon:'🔥',name:'Protector de racha',price:80,desc:'Protege tu racha durante un día si no puedes jugar.'},{id:'badge',icon:'👑',name:'Insignia exclusiva',price:120,desc:'Una insignia coleccionable para lucir en tu perfil.'}];
 const readInv=()=>{try{return {...{time10:0,fox:0,special:0,streak:0,badge:0},...JSON.parse(localStorage.getItem(INV_KEY)||'{}')}}catch(e){return {time10:0,fox:0,special:0,streak:0,badge:0}}};
 const writeInv=v=>{localStorage.setItem(INV_KEY,JSON.stringify(v));window.dispatchEvent(new CustomEvent('r60inventorychange',{detail:v}));return v};
 const count=id=>Math.max(0,Number(readInv()[id]||0));
 const add=(id,n=1)=>{const v=readInv();v[id]=Math.max(0,Number(v[id]||0)+Number(n||0));writeInv(v);return v[id]};
 const points=()=>Math.max(0,Number(localStorage.getItem('reto60points')||0));
 const setPoints=n=>{localStorage.setItem('reto60points',String(Math.max(0,Number(n)||0)));window.dispatchEvent(new Event('storage'));};
 const isTimeActive=()=>localStorage.getItem(ACTIVE_TIME_KEY)==='1';
 const activateTime=()=>{if(count('time10')<1)return false;localStorage.setItem(ACTIVE_TIME_KEY,'1');return true};
 const deactivateTime=()=>localStorage.removeItem(ACTIVE_TIME_KEY);
 const consumeTime=()=>{if(!isTimeActive()||count('time10')<1){deactivateTime();return false}const v=readInv();v.time10=Math.max(0,v.time10-1);writeInv(v);deactivateTime();if(window.reto60Cloud)window.reto60Cloud('consume_time10').then(syncInventory);return true};
 const isFoxEquipped=()=>localStorage.getItem(FOX_EQUIPPED_KEY)==='1'&&count('fox')>0;
 const equipFox=()=>{if(count('fox')<1)return false;localStorage.setItem(FOX_EQUIPPED_KEY,'1');if(window.reto60Cloud)window.reto60Cloud('set_fox_equipped',{equipped:true});return true};
 const unequipFox=()=>{localStorage.removeItem(FOX_EQUIPPED_KEY);if(window.reto60Cloud)window.reto60Cloud('set_fox_equipped',{equipped:false})};
 async function syncInventory(){if(!window.reto60Cloud)return false;const r=await window.reto60Cloud('get_inventory');if(!r.ok)return false;const v=readInv();v.time10=0;v.fox=0;(r.inventory||[]).forEach(x=>{if(x.item_id==='time10'||x.item_id==='fox')v[x.item_id]=Number(x.quantity||0);if(x.item_id==='fox'){if(x.equipped)localStorage.setItem(FOX_EQUIPPED_KEY,'1');else localStorage.removeItem(FOX_EQUIPPED_KEY)}});if(v.time10<1)deactivateTime();writeInv(v);return true}
 function close(){document.getElementById('r60Store')?.remove();document.getElementById('r60StoreCss')?.remove()}
 function css(){const s=document.createElement('style');s.id='r60StoreCss';s.textContent=`#r60Store{position:fixed;inset:0;z-index:100010;background:radial-gradient(circle at 50% 0,#17214d 0,#080c20 40%,#040713 100%);color:#fff;overflow:auto;font-family:Arial,sans-serif}.r60shop{max-width:620px;margin:auto;padding:18px 16px 42px}.r60top{display:flex;align-items:center;justify-content:space-between;gap:10px;position:sticky;top:0;z-index:3;padding:8px 0 14px;background:linear-gradient(#080c20 70%,transparent)}.r60back{border:1px solid #35417d;background:#141b3e;color:#fff;border-radius:14px;padding:11px 14px;font-weight:800}.r60wallet{background:#111936;border:1px solid #35417d;border-radius:14px;padding:10px 14px;font-weight:900;color:#ffd35a}.r60hero{text-align:center;padding:14px 8px 22px}.r60hero h1{font-size:30px;margin:6px}.r60hero p{color:#aeb7d7;margin:7px auto;max-width:430px;line-height:1.4}.r60tag{display:inline-block;background:#ffb800;color:#151515;border-radius:999px;padding:6px 11px;font-size:12px;font-weight:900}.r60section{font-size:14px;color:#aeb7d7;font-weight:900;letter-spacing:.08em;margin:18px 4px 10px}.r60grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.r60card{position:relative;overflow:hidden;background:linear-gradient(145deg,#151d43,#0d1330);border:1px solid #303c78;border-radius:22px;padding:18px;min-height:220px;box-shadow:0 12px 32px rgba(0,0,0,.22)}.r60card.feature{grid-column:span 2;min-height:190px;background:linear-gradient(135deg,#39220c,#191333 55%,#101735)}.r60icon{font-size:50px;filter:drop-shadow(0 7px 12px rgba(0,0,0,.25))}.r60kind{font-size:10px;color:#9da8cf;font-weight:900;letter-spacing:.1em;margin-top:8px}.r60name{font-size:19px;font-weight:900;margin:5px 0}.r60desc{font-size:13px;color:#b7bfdc;line-height:1.35;min-height:52px}.r60price{font-size:16px;color:#ffd35a;font-weight:900;margin:10px 0}.r60owned{position:absolute;right:12px;top:12px;background:#202a59;border:1px solid #42508f;border-radius:999px;padding:5px 8px;font-size:11px}.r60buy{width:100%;border:0;border-radius:13px;padding:12px;background:#ffb800;color:#17120a;font-weight:900;font-size:13px}.r60buy.secondary{background:#5967a9;color:white}.r60buy:disabled{opacity:.45}.r60note{margin-top:20px;border:1px solid #293565;background:#0e1532;border-radius:18px;padding:14px;color:#aeb7d7;font-size:12px;line-height:1.45}@media(max-width:430px){.r60grid{gap:10px}.r60card{padding:14px;min-height:215px}.r60name{font-size:17px}.r60hero h1{font-size:27px}}`;document.head.appendChild(s)}
 function buyPoints(id){const item=R60_PRODUCTS.find(x=>x.id===id);if(!item)return;if(points()<item.price){alert(`Te faltan ${item.price-points()} puntos R60 para conseguir ${item.name}.`);return;}setPoints(points()-item.price);add(id,1);render();}
 function productCard(p){const owned=count(p.id),action=p.id==='time10'?(owned?`<button class="r60buy secondary" data-action="time">${isTimeActive()?'✓ ACTIVADO':'ACTIVAR PARA PRÓXIMA PARTIDA'}</button>`:`<button class="r60buy" data-money="${p.id}">PRÓXIMAMENTE · ${p.price}</button>`):(owned?`<button class="r60buy secondary" data-action="fox">${isFoxEquipped()?'✓ ZORRO EQUIPADO':'EQUIPAR ZORRO'}</button>`:`<button class="r60buy" data-money="${p.id}">PRÓXIMAMENTE · ${p.price}</button>`);return `<article class="r60card ${p.id==='fox'?'feature':''}"><span class="r60owned">🎒 ${owned}</span><div class="r60icon">${p.icon}</div><div class="r60kind">${p.kind}</div><div class="r60name">${p.name}</div><div class="r60desc">${p.desc}</div><div class="r60price">${p.price}</div>${action}</article>`}
 function pointCard(p){return `<article class="r60card"><span class="r60owned">🎒 ${count(p.id)}</span><div class="r60icon">${p.icon}</div><div class="r60kind">RECOMPENSA R60</div><div class="r60name">${p.name}</div><div class="r60desc">${p.desc}</div><div class="r60price">⭐ ${p.price} puntos</div><button class="r60buy" data-points="${p.id}" ${points()<p.price?'disabled':''}>CANJEAR</button></article>`}
 function render(){const root=document.getElementById('r60Store');if(!root)return;root.innerHTML=`<main class="r60shop"><div class="r60top"><button class="r60back" id="r60StoreBack">← VOLVER</button><div class="r60wallet">⭐ ${points()} PUNTOS</div></div><section class="r60hero"><span class="r60tag">⚡ MERCADO R60</span><h1>🛒 Tienda Reto 60</h1><p>Convierte tus partidas en progreso. Equipa mascotas, prepara potenciadores y desbloquea recompensas.</p></section><div class="r60section">MASCOTAS Y POTENCIADORES</div><section class="r60grid">${PRODUCTS.map(productCard).join('')}</section><div class="r60section">CANJEA TUS PUNTOS</div><section class="r60grid">${R60_PRODUCTS.map(pointCard).join('')}</section><div class="r60note">🧪 <b>Versión Preview:</b> los canjes con puntos funcionan localmente para probar la experiencia. Las compras con dinero real permanecen desactivadas hasta completar la integración de pago.</div></main>`;root.querySelector('#r60StoreBack').onclick=close;root.querySelectorAll('[data-points]').forEach(b=>b.onclick=()=>buyPoints(b.dataset.points));root.querySelectorAll('[data-money]').forEach(b=>b.onclick=()=>alert('Esta compra todavía no está habilitada en Preview.'));root.querySelector('[data-action="time"]')?.addEventListener('click',()=>{if(isTimeActive())deactivateTime();else activateTime();render()});root.querySelector('[data-action="fox"]')?.addEventListener('click',()=>{if(isFoxEquipped())unequipFox();else equipFox();render()});}
 function open(){close();css();const root=document.createElement('div');root.id='r60Store';document.body.appendChild(root);render();syncInventory().then(ok=>{if(ok&&document.getElementById('r60Store'))render()}).catch(()=>{});}
 function install(){if(document.getElementById('r60StoreButton'))return true;const home=document.getElementById('home');if(!home)return false;const b=document.createElement('button');b.id='r60StoreButton';b.textContent='🛒 TIENDA · MASCOTAS Y POTENCIADORES';b.onclick=open;home.appendChild(b);return true}
 window.R60Store={open,close,install,products:PRODUCTS,r60Products:R60_PRODUCTS,inventory:readInv,count,add,syncInventory,isTimeActive,activateTime,deactivateTime,consumeTime,isFoxEquipped,equipFox,unequipFox};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();